import { useRouter } from "next/router";
import React, { useEffect } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Layout, Posts, LoadingSpinner } from "@/components/Index";
import { fetchPosts } from "@/redux/reducer/posts";

function PostIndex() {
  const router = useRouter();
  const { pages } = router.query;

  const dispatch = useDispatch();

  const posts = useSelector((state) => state.posts.posts);
  const user = useSelector((state) => state.user.user);

  const postStatus = useSelector((state) => state.posts.status);

  let content;
  if (postStatus === "loading") {
    content = (
      <div
        className="container-fluid d-flex align-items-center justify-content-center"
        style={{ height: "100vh" }}
      >
        <LoadingSpinner />;
      </div>
    );
  } else if (postStatus === "succeeded") {
    content = <Posts data={posts} user={user} />;
  } else if (postStatus === "failed") {
    content = (
      <div>
        <p>Error happens</p>
      </div>
    );
  }

  useEffect(() => {
    if (postStatus === "idle") {
      dispatch(fetchPosts());
    }
  }, [postStatus, dispatch]);

  return (
    <>
      <Head>
        <title>Memories App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{content}</main>
    </>
  );
}

export default PostIndex;

PostIndex.getLayout = function getLayout(PostIndex) {
  return <Layout>{PostIndex}</Layout>;
};
