import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { Layout, LoadingSpinner, Posts } from "@/components/Index";
import { fetchPosts } from "@/redux/reducer/posts";

function useQuery() {
  return new URLSearchParams(useRouter().search);
}

export default function Home() {
  const dispatch = useDispatch();

  const posts = useSelector((state) => state.posts.posts);
  const user = useSelector((state) => state.user.user);

  const postStatus = useSelector((state) => state.posts.status);

  const query = useQuery();
  const page = query.get("page") || 1;
  const searchQuery = query.get("searchQuery");

  let content;
  if (postStatus === "loading") {
    content = (
      <div
        className="container-fluid d-flex align-items-center justify-content-center"
        style={{ height: "100vh" }}
      >
        <LoadingSpinner />;
      </div>
    );
  } else if (postStatus === "succeeded") {
    content = <Posts data={posts} user={user} />;
  } else if (postStatus === "failed") {
    content = (
      <div>
        <p>Error happens</p>
        {error}
      </div>
    );
  }

  useEffect(() => {
    if (postStatus === "idle") {
      dispatch(fetchPosts());
    }
  }, [postStatus, dispatch]);

  return (
    <>
      <Head>
        <title>Memories App</title>
        <title>Memories App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{content}</main>
    </>
  );
}

Home.getLayout = function getLayout(Home) {
  return <Layout>{Home}</Layout>;
};
