import Head from "next/head";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import InputForm from "@/components/Form";
import AppBar from "@/components/AppBar";
import Posts from "@/components/Posts";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchPosts } from "@/redux/reducer/posts";

export default function Home() {
  const dispatch = useDispatch();
  const posts = useSelector((state) => state.posts.posts);

  useEffect(() => {
    dispatch(fetchPosts());
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Pensive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* Font Awesome  */}
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.2/css/all.css"
          integrity="sha384-fZCoUih8XsaUZnNDOiLqnby1tMJ0sE7oBbNk2Xxf5x8Z4SvNQ9j83vFMa/erbVrV"
          crossOrigin="anonymous"
        />
        {/* TODO: find alternate to render fontawesome icons */}
      </Head>
      <main>
        <Container>
          <AppBar />
          <Row>
            <Col xs={12} md={6} lg={8}>
              <Posts data={posts} />
            </Col>
            <Col xs={12} md={6} lg={4}>
              <InputForm />
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}
